import Head from "next/head";

import { PROJECT_NAME } from "../../config";
import Logo from "./Logo";
import ThemeToggle from "./ThemeToggle";
import { Header } from "./Header";

const Layout = ({ children }: { children: any }) => {
  return (
    <div
      data-theme
      // className="min-h-screen bg-gradient-to-r from-purple-500 to-pink-500"
      // className="bg-pink-500"
      className="min-h-full bg-[url('../public/Linear5-Grain2.png')] bg-cover bg-center"
    >
      <Head>
        <title>{PROJECT_NAME}</title>
        <meta name="description" content="Generated by create-teddy-bear" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>

      <body>
        {/* <div className="navbar bg-base-200">
          <Logo />
          <div className="flex-none sm:hidden">
            <button className="btn btn-square btn-ghost">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                className="inline-block w-5 h-5 stroke-current"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M4 6h16M4 12h16M4 18h16"
                ></path>
              </svg>
            </button>
          </div>
          <div className="hidden sm:flex">
            <ThemeToggle />
            <ConnectButton />
          </div>
        </div> */}
        <Header />

        {children}
      </body>
      <footer></footer>
    </div>
  );
};

export default Layout;
