import Head from "next/head";

import { PROJECT_NAME } from "../../config";
import { Header } from "./Header";

const Layout = ({ children }: { children: any }) => {
  return (
    <div
      data-theme
      className="bg-[url('../public/Linear5-Grain2.png')] bg-cover bg-center"
    >
      <Head>
        <title>{PROJECT_NAME}</title>
        <meta name="description" content="Generated by create-teddy-bear" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
      </Head>

      <div className="h-screen">
        <Header />
        {children}
      </div>
    </div>
  );
};

export default Layout;
